### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by yyyyyyyy0224** [KingJamesSong/RankFeat#2]
Great work！Can you share the code for the visualization in Figure 2？ I want to do this but don't know how to do...Thanks
Below is Figure 2
![image](https://github.com/KingJamesSong/RankFeat/assets/55536926/2f90df54-e3a6-4ef6-a556-5830a5559284)

**Comment by KingJamesSong** [comment]
Hi,
  
  Thanks for your interest!

  I attached the Matlab code for visualization as below:

  in_scores = importdata('./feat_cond/in_trainid_dtd.txt');
  out_scores = importdata('./feat_cond/out_trainid_dtd.txt');
  figure
  histogram(in_scores,100,'Normalization','probability');
  hold on;
  histogram(out_scores,100,'Normalization','probability');
hold off
legend('ID Data','OOD Data','FontSize',14)
xlabel('Scores')
ylabel('Frequency')
title('RankFeat+ Score Distribution on Textures Testset','FontSize',16)

 First you need to store the OOD scores in a text file and then use the above codes for visualization.
