### ISSUE TITLE
How to find whether an image is In-distribution or OOD at Inference?

### ISSUE THREAD

**Issue by DheerajMaddaR** [KingJamesSong/RankFeat#3]
Given a single image at inference, how we can identify whether it is an In-distribution or OOD? There should be some thresholding to decide this right?

**Comment by KingJamesSong** [comment]
Thanks for your question.

Yes, you can find the distribution of ID scores and calculate the percentile by 95% (for example). 
```
np.percentile(in_scores.flatten(), 95)
```
Then you can get the threshold.
